### ISSUE TITLE
The plugin doesn't appear

### ISSUE THREAD

**Issue by Anjanibalqis** [SMByC/AcATaMa#11]
Hi! I already installed the AcATaMa plugin, but when I clicked  the table content doesn't appear on the screen. Could you tell me, what I should do about this issue? 

https://user-images.githubusercontent.com/97080846/148028242-08d374d8-0172-41e7-b31d-3ba08baf4c31.mp4

**Comment by XavierCLL** [comment]
Hi @Anjanibalqis,

Which Qgis version are you using? reinstall the plugin and try again, check if any error is showing

**Comment by Anjanibalqis** [comment]
> Hi @Anjanibalqis,
> 
> Which Qgis version are you using? reinstall the plugin and try again, check if any error is showing

I'm using the 3.22 version. I already reinstall the plugin several times, but it's still not appearing. The error shown  python error, but I don't understand where's the error
![Screenshot (4)](https://user-images.githubusercontent.com/97080846/148166906-aa4579fa-c5bf-409a-b6bc-d79f2f120fc1.png)

**Comment by Anjanibalqis** [comment]
Hi, I would like to update you my situation. I reinstall the app the plugin is working really well. Thank you so much for your help :)
