### ISSUE TITLE
'AccuracyAssessment' object has no attribute 'samples_outside_the_thematic'

### ISSUE THREAD

**Issue by pgarcia2021** [SMByC/AcATaMa#13]
Greetings, I am getting this error when trying to generate the confusion matrix... what could it be due to?
Traceback (most recent call last):
  File "C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AcATaMa\utils\system_utils.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AcATaMa\gui\accuracy_assessment_results.py", line 86, in get_html
    if accu_asse.samples_outside_the_thematic:
AttributeError: 'AccuracyAssessment' object has no attribute 'samples_outside_the_thematic'

**Comment by XavierCLL** [comment]
Hi,
That is a weird bug, try first saving the Acatama state, restart the Qgis, load the Acatama state and try again.

**Comment by JDFV** [comment]
Hi, 
in some cases this bug, happens when you work with big information in the thematic. Save the state and try with a power computer. it may help

**Comment by XavierCLL** [comment]
Hi @JDFV thanks so much for providing more information about this problem. In addition, this weird bug was fixed in the new version which is very close to release.

**Comment by XavierCLL** [comment]
fixed in the latest version, feel free to open it again if the issue persists
