### ISSUE TITLE
Issue using AcATaMa version 24.10 with Qgis version 3.28.7-Firenze and Python 3.9.5 

### ISSUE THREAD

**Issue by gmrstrenzel** [SMByC/AcATaMa#23]
I received this error message when performing sampling design. It happens when I press "Generate samples" button. Due that issue the "Computation of accuracy assessment" don't works. 

"AcATaMa: 'sip.enumtype' object is not iterable"

Details:

Traceback (most recent call last):
  File "C:\Users/gmrs/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AcATaMa\utils\system_utils.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "C:\Users/gmrs/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AcATaMa\core\sampling_design.py", line 166, in simple_random_sampling_finished
    sampling_report = SamplingReport(sampling_layer_generated, sampling, sampling_conf)
  File "C:\Users/gmrs/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AcATaMa\gui\sampling_report.py", line 88, in __init__
    for area_unit in sorted(QgsUnitTypes.AreaUnit, key=lambda x: x.value):
TypeError: 'sip.enumtype' object is not iterable

![image](https://github.com/user-attachments/assets/d62aa46e-fdde-4c28-b3c5-b49d2e5b6a4f)

**Comment by XavierCLL** [comment]
Hi @gmrstrenzel 

Thanks for reporting that issue. The same issue was already reported here #22, the error comes from the Qgis Area Unit types, in the latest version of the plugin I changed an old code to use a better way to manage the area unit using a Qgis function introduced in Qgis 3.30. So please update the Qgis to the LTR version at least (recommended) or the latest one.

Sorry for introducing a change that doesn't work with a very old version of Qgis :/

Regards,
Xavier

**Comment by XavierCLL** [comment]
@gmrstrenzel I'm going to close this bug, but you can open it again if the bug persists after updating the QGIS.
