### ISSUE TITLE
About text question

### ISSUE THREAD

**Issue by jakimowb** [SMByC/AcATaMa#3]
The about text mentions "ThRasE", but the acronym it is not further explained:

> About us
ThRasE was developing, designed and implemented by the Group of Forest and Carbon Monitoring System (SMByC), operated by the Institute of Hydrology, Meteorology and Environmental Studies (IDEAM) - Colombia. 

Seems like ThRasE is a former name of AcATaMa and the about text needs to be updated?

**Comment by XavierCLL** [comment]
Hi jakimowb, you are right, it was a silly mistake, I'm developing the ThRasE plugin too and I copied that text from it. Thanks for bothering you to open an issue about it, I appreciate it.
