### ISSUE TITLE
Cannot set the minimum distance between samples when doing random sampling

### ISSUE THREAD

**Issue by hoangthanhtung-imhen** [SMByC/AcATaMa#4]
The plugin works well with the minimum distance = 0.
Whatever non-zero minimum distance is set, this error message comes:
```
Traceback (most recent call last):
  File "/home/tung/.local/share/QGIS/QGIS3/profiles/default/python/plugins/AcATaMa/utils/system_utils.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "/home/tung/.local/share/QGIS/QGIS3/profiles/default/python/plugins/AcATaMa/core/sampling.py", line 224, in do_stratified_random_sampling
    if sampling.total_of_samples < total_of_samples and sampling.total_of_samples > 0:
TypeError: unorderable types: NoneType() < int()
```

I use QGIS 3.4, OS Ubuntu 16.04, AcATaMa v19.11.21 
Please check.

**Comment by XavierCLL** [comment]
Hi,
Thanks for the report,
That is weird, I think the problem is not the minimum distance, is the number of samples, what is the total number of samples? could you please take a screenshot with the all option set in the sampling generation tab?

**Comment by hoangthanhtung-imhen** [comment]
Hi Xavier
For example, I do simple random sampling with this classification map: https://drive.google.com/file/d/1nOyWEoONF3AyQHOFN1aqMlU6VmQnmhaT/view?usp=sharing
I set the total number of samples is 20, minimum distance is 100m.

![acatama](https://user-images.githubusercontent.com/32954904/80940577-2db02080-8e1b-11ea-8b49-3bb58ca48b25.jpg)

**Comment by XavierCLL** [comment]
Hi,
I see that your layer is in EPSG:4326 and right now Acatama doesn't support minimum distance in "degrees" then reproject your layer to a valid metric coordinate system. Please confirm if that is the problem or not.

**Comment by hoangthanhtung-imhen** [comment]
Hi Xavier,
The problem stil present when in metric coordinate system. EPSG:32757
![image](https://user-images.githubusercontent.com/32954904/81046590-b1d5d700-8ef3-11ea-9841-0ab2b3397ac6.png)

**Comment by XavierCLL** [comment]
I've tested your image in my laptop and it works perfectly, maybe that error is specific for the Qgis version or python version that are you using, I need to test it more to try to reproduce the error...

![image](https://user-images.githubusercontent.com/11801453/81095489-ecbb1900-8eb9-11ea-8b73-a1e5d54a8d5a.png)

**Comment by XavierCLL** [comment]
Hi, I couldn't reproduce the error using the same files, so I think that this error is very specific for the old version of your Ubuntu (I recommend update it, or install/use Qgis in an Anaconda environment to have latest python libs version). Please open it again if the error persists.

**Comment by hoangthanhtung-imhen** [comment]
Dear Mr. Xavier,
Thank you very much for your support. I will handle it as your suggestion.
Yours sincerely
--------------------------
Hoang Thanh Tung
